# Generated by Django 5.0.2 on 2024-03-17 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='stipe_charge_id',
            new_name='stripe_charge_id',
        ),
    ]
