# Generated by Django 5.0.2 on 2024-03-17 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0002_rename_stipe_charge_id_payment_stripe_charge_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_charge_id',
            new_name='stipe_charge_id',
        ),
    ]
